--- arch/arm/mach-msm/lge/Makefile
+++ arch/arm/mach-msm/lge/Makefile
@@ -5,7 +5,7 @@
 #obj-y += board-swift.o
 #obj-y += board-swift-keypad.o
 #obj-y += board-swift-gpio-i2c.o
-#obj-y += board-swift-vibrator.o
+obj-y += board-swift-vibrator.o
 obj-y += board-swift-leds.o
 #obj-y += board-swift-msensor-bma150.o
 #obj-y += board-swift-ec-ak8973.o
